let os = Sys.os_type
let version = "0.1"
let system = "linux"
let arch = "amd64"
let name = "jamler"
let ocaml = Sys.ocaml_version
let synopsis = "OCaml Jabber Server"
let copyright = "Copyright (c) 2002-2011 ProcessOne"
let uri = "http://www.process-one.net/en/jamler/"
let bday = "2011-05-30"
